version: '3'


vars:
  OS_CLIENT_CONFIG_FILE: '{{.HOME}}/.config/openstack/clouds.yaml'
  OS_CLOUD: 'idcs-stage-dev@stratuslab.production.virtualdata'
  DOTENV_PATH: '.env'

tasks:

  default:
    cmds:
    - task --list

  build:
    desc: build the binary file for the backend
    dir: microservices/openstack
    sources:
    - "**/*.go"
    generates:
    - ./bin/app .
    cmds:
    - go mod tidy
    - echo "building app"
    - go build -o ./bin/app .

  backend:
    deps: [build]
    dir: microservices/openstack
    cmds:
      - |
        export OS_CLIENT_CONFIG_FILE={{.OS_CLIENT_CONFIG_FILE}}
        export OS_CLOUD={{.OS_CLOUD}}
        export PORT=8080
        export DOTENV_PATH={{.DOTENV_PATH}}
        #export GIN_MODE=release
        ./bin/app

  frontend:
    dir:  newfront
    cmds:
      - npm run dev

  frontexpose:
    dir: newfront
    cmds:
      - npm run dev -- --host

  control:
    dir: control_center
    cmds:
    - go run main.go

  run:
    desc: run the binary file, build it if not existed
    cmds:
      - task backend &
      - task frontend
      

  clean:
    desc: delete binary file
    cmds:
    - 
      rm -rf ./microservices/openstack/bin
      rm ./microservices/openstack/PoolManagerVM.db

  cli:
    desc: cli
    cmds:
    - |
      export OS_CLIENT_CONFIG_FILE={{.OS_CLIENT_CONFIG_FILE}}
      export OS_CLOUD={{.OS_CLOUD}}
      pkgx openstack