version: '3'


vars:
  DOTENV_PATH: '.env'

tasks:

  default:
    cmds:
    - task --list

  check_clouds:
    desc: "Vérifie que le fichier clouds.yaml existe"
    cmds:
      - '[ -f {{.OS_CLIENT_CONFIG_FILE}} ] || { echo "❌ clouds.yaml introuvable à {{.OS_CLIENT_CONFIG_FILE}}"; exit 1; }'

  setup :
    desc: setup project 
    cmds:
    - '[ ! -f go.mod ] && go mod init github.com/tonpseudo/monprojet || echo "go.mod exists"'
    - 'go get github.com/charmbracelet/huh@latest'
    - 'go run config.go'
    - task check_clouds
    - task init_control
    - task init_micro

  init_control:
    dir: control_center
    cmds:
      - '[ ! -f go.mod ] && go mod init control_center || echo "go.mod exists"'

  init_micro:
    dir: microservices/openstack
    cmds:
      - '[ ! -f go.mod ] && go mod init PoolManagerVM/backend || echo "go.mod exists"'

  build:
    desc: build the binary file for the backend
    dir: microservices/openstack
    sources:
    - "**/*.go"
    generates:
    - ./bin/app .
    cmds:
    - go mod tidy
    - echo "building app"
    - go build -o ./bin/app .

  backend:
    deps: [build, check_clouds]
    dir: microservices/openstack
    cmds:
      - |
        export PORT=8080
        export DOTENV_PATH={{.DOTENV_PATH}}
        #export GIN_MODE=release
        ./bin/app

  frontend:
    dir:  newfront
    cmds:
      - npm run dev

  frontexpose:
    dir: newfront
    cmds:
      - npm run dev -- --host

  control:
    dir: control_center
    cmds:
    - go run main.go

  run:
    desc: run the binary file, build it if not existed
    cmds:
      - task backend &
      - task frontend
      

  clean:
    desc: delete binary file
    cmds:
    - 
      rm -rf ./microservices/openstack/bin
      rm ./microservices/openstack/PoolManagerVM.db

  dev:
    desc: "Lance tout le soft (backend → control → frontend)"
    cmds:
      - |
        tmux new-session -d -s soft

        tmux rename-window -t soft:0 backend
        tmux send-keys -t soft:backend "task backend" C-m

        tmux new-window -t soft -n control
        tmux send-keys -t soft:control \
          "until nc -z localhost 50052; do echo '...'; sleep 1; done && task control" C-m

        tmux new-window -t soft -n frontend
        tmux send-keys -t soft:frontend "task frontexpose" C-m

        tmux attach -t soft


  cli:
    desc: cli
    cmds:
    - |
      export OS_CLIENT_CONFIG_FILE={{.OS_CLIENT_CONFIG_FILE}}
      export OS_CLOUD={{.OS_CLOUD}}
      pkgx openstack