// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: poolmanager.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNKNOWN Status = 0
	Status_CREATE         Status = 1
	Status_UPDATE         Status = 2
	Status_DELETE         Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "CREATE",
		2: "UPDATE",
		3: "DELETE",
	}
	Status_value = map[string]int32{
		"STATUS_UNKNOWN": 0,
		"CREATE":         1,
		"UPDATE":         2,
		"DELETE":         3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_poolmanager_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_poolmanager_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_poolmanager_proto_rawDescGZIP(), []int{0}
}

type Type int32

const (
	Type_TYPE_UNKNOWN Type = 0
	Type_SERVERPOOL   Type = 1
	Type_SERVER       Type = 2
	Type_CONFIG       Type = 3
	Type_USER         Type = 4
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "TYPE_UNKNOWN",
		1: "SERVERPOOL",
		2: "SERVER",
		3: "CONFIG",
		4: "USER",
	}
	Type_value = map[string]int32{
		"TYPE_UNKNOWN": 0,
		"SERVERPOOL":   1,
		"SERVER":       2,
		"CONFIG":       3,
		"USER":         4,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_poolmanager_proto_enumTypes[1].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_poolmanager_proto_enumTypes[1]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_poolmanager_proto_rawDescGZIP(), []int{1}
}

type RessourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Data          map[string]string      `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status        Status                 `protobuf:"varint,3,opt,name=status,proto3,enum=poolmanager.Status" json:"status,omitempty"`
	Type          Type                   `protobuf:"varint,4,opt,name=type,proto3,enum=poolmanager.Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RessourceRequest) Reset() {
	*x = RessourceRequest{}
	mi := &file_poolmanager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RessourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RessourceRequest) ProtoMessage() {}

func (x *RessourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poolmanager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RessourceRequest.ProtoReflect.Descriptor instead.
func (*RessourceRequest) Descriptor() ([]byte, []int) {
	return file_poolmanager_proto_rawDescGZIP(), []int{0}
}

func (x *RessourceRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *RessourceRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RessourceRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNKNOWN
}

func (x *RessourceRequest) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_TYPE_UNKNOWN
}

type RessourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RessourceResponse) Reset() {
	*x = RessourceResponse{}
	mi := &file_poolmanager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RessourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RessourceResponse) ProtoMessage() {}

func (x *RessourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poolmanager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RessourceResponse.ProtoReflect.Descriptor instead.
func (*RessourceResponse) Descriptor() ([]byte, []int) {
	return file_poolmanager_proto_rawDescGZIP(), []int{1}
}

func (x *RessourceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_poolmanager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poolmanager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_poolmanager_proto_rawDescGZIP(), []int{2}
}

func (x *UserRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type StreamRessourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=poolmanager.Status" json:"status,omitempty"`
	Type          Type                   `protobuf:"varint,3,opt,name=type,proto3,enum=poolmanager.Type" json:"type,omitempty"`
	Data          map[string]string      `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRessourceResponse) Reset() {
	*x = StreamRessourceResponse{}
	mi := &file_poolmanager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRessourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRessourceResponse) ProtoMessage() {}

func (x *StreamRessourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poolmanager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRessourceResponse.ProtoReflect.Descriptor instead.
func (*StreamRessourceResponse) Descriptor() ([]byte, []int) {
	return file_poolmanager_proto_rawDescGZIP(), []int{3}
}

func (x *StreamRessourceResponse) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *StreamRessourceResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNKNOWN
}

func (x *StreamRessourceResponse) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_TYPE_UNKNOWN
}

func (x *StreamRessourceResponse) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type Image struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status           string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Tags             string                 `protobuf:"bytes,4,opt,name=tags,proto3" json:"tags,omitempty"` // CSV format
	ContainerFormat  string                 `protobuf:"bytes,5,opt,name=container_format,json=containerFormat,proto3" json:"container_format,omitempty"`
	DiskFormat       string                 `protobuf:"bytes,6,opt,name=disk_format,json=diskFormat,proto3" json:"disk_format,omitempty"`
	MinDiskGigabytes int32                  `protobuf:"varint,7,opt,name=min_disk_gigabytes,json=minDiskGigabytes,proto3" json:"min_disk_gigabytes,omitempty"`
	MinRamMegabytes  int32                  `protobuf:"varint,8,opt,name=min_ram_megabytes,json=minRamMegabytes,proto3" json:"min_ram_megabytes,omitempty"`
	Owner            string                 `protobuf:"bytes,9,opt,name=owner,proto3" json:"owner,omitempty"`
	Protected        bool                   `protobuf:"varint,10,opt,name=protected,proto3" json:"protected,omitempty"`
	Visibility       string                 `protobuf:"bytes,11,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Hidden           bool                   `protobuf:"varint,12,opt,name=hidden,proto3" json:"hidden,omitempty"`
	Checksum         string                 `protobuf:"bytes,13,opt,name=checksum,proto3" json:"checksum,omitempty"`
	SizeBytes        int64                  `protobuf:"varint,14,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	File             string                 `protobuf:"bytes,17,opt,name=file,proto3" json:"file,omitempty"`
	Schema           string                 `protobuf:"bytes,18,opt,name=schema,proto3" json:"schema,omitempty"`
	VirtualSize      int64                  `protobuf:"varint,19,opt,name=virtual_size,json=virtualSize,proto3" json:"virtual_size,omitempty"`
	ImportMethods    string                 `protobuf:"bytes,20,opt,name=import_methods,json=importMethods,proto3" json:"import_methods,omitempty"` // CSV format
	StoreIds         string                 `protobuf:"bytes,21,opt,name=store_ids,json=storeIds,proto3" json:"store_ids,omitempty"`                // CSV format
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_poolmanager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_poolmanager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_poolmanager_proto_rawDescGZIP(), []int{4}
}

func (x *Image) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Image) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Image) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Image) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *Image) GetContainerFormat() string {
	if x != nil {
		return x.ContainerFormat
	}
	return ""
}

func (x *Image) GetDiskFormat() string {
	if x != nil {
		return x.DiskFormat
	}
	return ""
}

func (x *Image) GetMinDiskGigabytes() int32 {
	if x != nil {
		return x.MinDiskGigabytes
	}
	return 0
}

func (x *Image) GetMinRamMegabytes() int32 {
	if x != nil {
		return x.MinRamMegabytes
	}
	return 0
}

func (x *Image) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Image) GetProtected() bool {
	if x != nil {
		return x.Protected
	}
	return false
}

func (x *Image) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *Image) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *Image) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *Image) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Image) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Image) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Image) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Image) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *Image) GetVirtualSize() int64 {
	if x != nil {
		return x.VirtualSize
	}
	return 0
}

func (x *Image) GetImportMethods() string {
	if x != nil {
		return x.ImportMethods
	}
	return ""
}

func (x *Image) GetStoreIds() string {
	if x != nil {
		return x.StoreIds
	}
	return ""
}

type Flavor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Disk          int32                  `protobuf:"varint,3,opt,name=disk,proto3" json:"disk,omitempty"`
	Ram           int32                  `protobuf:"varint,4,opt,name=ram,proto3" json:"ram,omitempty"`
	Vcpus         int32                  `protobuf:"varint,5,opt,name=vcpus,proto3" json:"vcpus,omitempty"`
	RxtxFactor    float64                `protobuf:"fixed64,6,opt,name=rxtx_factor,json=rxtxFactor,proto3" json:"rxtx_factor,omitempty"`
	Swap          int32                  `protobuf:"varint,7,opt,name=swap,proto3" json:"swap,omitempty"`
	Ephemeral     int32                  `protobuf:"varint,8,opt,name=ephemeral,proto3" json:"ephemeral,omitempty"`
	IsPublic      bool                   `protobuf:"varint,9,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	Description   string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	ExtraSpecs    string                 `protobuf:"bytes,11,opt,name=extra_specs,json=extraSpecs,proto3" json:"extra_specs,omitempty"` // JSON serialized
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flavor) Reset() {
	*x = Flavor{}
	mi := &file_poolmanager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flavor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flavor) ProtoMessage() {}

func (x *Flavor) ProtoReflect() protoreflect.Message {
	mi := &file_poolmanager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flavor.ProtoReflect.Descriptor instead.
func (*Flavor) Descriptor() ([]byte, []int) {
	return file_poolmanager_proto_rawDescGZIP(), []int{5}
}

func (x *Flavor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Flavor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Flavor) GetDisk() int32 {
	if x != nil {
		return x.Disk
	}
	return 0
}

func (x *Flavor) GetRam() int32 {
	if x != nil {
		return x.Ram
	}
	return 0
}

func (x *Flavor) GetVcpus() int32 {
	if x != nil {
		return x.Vcpus
	}
	return 0
}

func (x *Flavor) GetRxtxFactor() float64 {
	if x != nil {
		return x.RxtxFactor
	}
	return 0
}

func (x *Flavor) GetSwap() int32 {
	if x != nil {
		return x.Swap
	}
	return 0
}

func (x *Flavor) GetEphemeral() int32 {
	if x != nil {
		return x.Ephemeral
	}
	return 0
}

func (x *Flavor) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *Flavor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Flavor) GetExtraSpecs() string {
	if x != nil {
		return x.ExtraSpecs
	}
	return ""
}

type Network struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description           string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AdminStateUp          bool                   `protobuf:"varint,4,opt,name=admin_state_up,json=adminStateUp,proto3" json:"admin_state_up,omitempty"`
	Status                string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	TenantId              string                 `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ProjectId             string                 `protobuf:"bytes,7,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Shared                bool                   `protobuf:"varint,8,opt,name=shared,proto3" json:"shared,omitempty"`
	RevisionNumber        int32                  `protobuf:"varint,9,opt,name=revision_number,json=revisionNumber,proto3" json:"revision_number,omitempty"`
	Subnets               string                 `protobuf:"bytes,10,opt,name=subnets,proto3" json:"subnets,omitempty"`                                                            // CSV
	AvailabilityZoneHints string                 `protobuf:"bytes,11,opt,name=availability_zone_hints,json=availabilityZoneHints,proto3" json:"availability_zone_hints,omitempty"` // CSV
	Tags                  string                 `protobuf:"bytes,12,opt,name=tags,proto3" json:"tags,omitempty"`                                                                  // CSV
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Network) Reset() {
	*x = Network{}
	mi := &file_poolmanager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network) ProtoMessage() {}

func (x *Network) ProtoReflect() protoreflect.Message {
	mi := &file_poolmanager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network.ProtoReflect.Descriptor instead.
func (*Network) Descriptor() ([]byte, []int) {
	return file_poolmanager_proto_rawDescGZIP(), []int{6}
}

func (x *Network) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Network) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Network) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Network) GetAdminStateUp() bool {
	if x != nil {
		return x.AdminStateUp
	}
	return false
}

func (x *Network) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Network) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Network) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Network) GetShared() bool {
	if x != nil {
		return x.Shared
	}
	return false
}

func (x *Network) GetRevisionNumber() int32 {
	if x != nil {
		return x.RevisionNumber
	}
	return 0
}

func (x *Network) GetSubnets() string {
	if x != nil {
		return x.Subnets
	}
	return ""
}

func (x *Network) GetAvailabilityZoneHints() string {
	if x != nil {
		return x.AvailabilityZoneHints
	}
	return ""
}

func (x *Network) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

var File_poolmanager_proto protoreflect.FileDescriptor

const file_poolmanager_proto_rawDesc = "" +
	"\n" +
	"\x11poolmanager.proto\x12\vpoolmanager\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf0\x01\n" +
	"\x10RessourceRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12;\n" +
	"\x04data\x18\x02 \x03(\v2'.poolmanager.RessourceRequest.DataEntryR\x04data\x12+\n" +
	"\x06status\x18\x03 \x01(\x0e2\x13.poolmanager.StatusR\x06status\x12%\n" +
	"\x04type\x18\x04 \x01(\x0e2\x11.poolmanager.TypeR\x04type\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"-\n" +
	"\x11RessourceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"!\n" +
	"\vUserRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\"\xfe\x01\n" +
	"\x17StreamRessourceResponse\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12+\n" +
	"\x06status\x18\x02 \x01(\x0e2\x13.poolmanager.StatusR\x06status\x12%\n" +
	"\x04type\x18\x03 \x01(\x0e2\x11.poolmanager.TypeR\x04type\x12B\n" +
	"\x04data\x18\x04 \x03(\v2..poolmanager.StreamRessourceResponse.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xad\x05\n" +
	"\x05Image\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04tags\x18\x04 \x01(\tR\x04tags\x12)\n" +
	"\x10container_format\x18\x05 \x01(\tR\x0fcontainerFormat\x12\x1f\n" +
	"\vdisk_format\x18\x06 \x01(\tR\n" +
	"diskFormat\x12,\n" +
	"\x12min_disk_gigabytes\x18\a \x01(\x05R\x10minDiskGigabytes\x12*\n" +
	"\x11min_ram_megabytes\x18\b \x01(\x05R\x0fminRamMegabytes\x12\x14\n" +
	"\x05owner\x18\t \x01(\tR\x05owner\x12\x1c\n" +
	"\tprotected\x18\n" +
	" \x01(\bR\tprotected\x12\x1e\n" +
	"\n" +
	"visibility\x18\v \x01(\tR\n" +
	"visibility\x12\x16\n" +
	"\x06hidden\x18\f \x01(\bR\x06hidden\x12\x1a\n" +
	"\bchecksum\x18\r \x01(\tR\bchecksum\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x0e \x01(\x03R\tsizeBytes\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x12\n" +
	"\x04file\x18\x11 \x01(\tR\x04file\x12\x16\n" +
	"\x06schema\x18\x12 \x01(\tR\x06schema\x12!\n" +
	"\fvirtual_size\x18\x13 \x01(\x03R\vvirtualSize\x12%\n" +
	"\x0eimport_methods\x18\x14 \x01(\tR\rimportMethods\x12\x1b\n" +
	"\tstore_ids\x18\x15 \x01(\tR\bstoreIds\"\x9b\x02\n" +
	"\x06Flavor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04disk\x18\x03 \x01(\x05R\x04disk\x12\x10\n" +
	"\x03ram\x18\x04 \x01(\x05R\x03ram\x12\x14\n" +
	"\x05vcpus\x18\x05 \x01(\x05R\x05vcpus\x12\x1f\n" +
	"\vrxtx_factor\x18\x06 \x01(\x01R\n" +
	"rxtxFactor\x12\x12\n" +
	"\x04swap\x18\a \x01(\x05R\x04swap\x12\x1c\n" +
	"\tephemeral\x18\b \x01(\x05R\tephemeral\x12\x1b\n" +
	"\tis_public\x18\t \x01(\bR\bisPublic\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12\x1f\n" +
	"\vextra_specs\x18\v \x01(\tR\n" +
	"extraSpecs\"\xf0\x02\n" +
	"\aNetwork\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12$\n" +
	"\x0eadmin_state_up\x18\x04 \x01(\bR\fadminStateUp\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"project_id\x18\a \x01(\tR\tprojectId\x12\x16\n" +
	"\x06shared\x18\b \x01(\bR\x06shared\x12'\n" +
	"\x0frevision_number\x18\t \x01(\x05R\x0erevisionNumber\x12\x18\n" +
	"\asubnets\x18\n" +
	" \x01(\tR\asubnets\x126\n" +
	"\x17availability_zone_hints\x18\v \x01(\tR\x15availabilityZoneHints\x12\x12\n" +
	"\x04tags\x18\f \x01(\tR\x04tags*@\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06CREATE\x10\x01\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x03*J\n" +
	"\x04Type\x12\x10\n" +
	"\fTYPE_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"SERVERPOOL\x10\x01\x12\n" +
	"\n" +
	"\x06SERVER\x10\x02\x12\n" +
	"\n" +
	"\x06CONFIG\x10\x03\x12\b\n" +
	"\x04USER\x10\x042\xd2\x03\n" +
	"\vPoolManager\x12O\n" +
	"\x0eSendRessources\x12\x1d.poolmanager.RessourceRequest\x1a\x1e.poolmanager.RessourceResponse\x12U\n" +
	"\x13GetStreamRessources\x12\x16.google.protobuf.Empty\x1a$.poolmanager.StreamRessourceResponse0\x01\x12[\n" +
	"\x17GetStreamRessourcesUser\x12\x18.poolmanager.UserRequest\x1a$.poolmanager.StreamRessourceResponse0\x01\x12<\n" +
	"\fGetAllImages\x12\x16.google.protobuf.Empty\x1a\x12.poolmanager.Image0\x01\x12>\n" +
	"\rGetAllFlavors\x12\x16.google.protobuf.Empty\x1a\x13.poolmanager.Flavor0\x01\x12@\n" +
	"\x0eGetAllNetworks\x12\x16.google.protobuf.Empty\x1a\x14.poolmanager.Network0\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_poolmanager_proto_rawDescOnce sync.Once
	file_poolmanager_proto_rawDescData []byte
)

func file_poolmanager_proto_rawDescGZIP() []byte {
	file_poolmanager_proto_rawDescOnce.Do(func() {
		file_poolmanager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_poolmanager_proto_rawDesc), len(file_poolmanager_proto_rawDesc)))
	})
	return file_poolmanager_proto_rawDescData
}

var file_poolmanager_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_poolmanager_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_poolmanager_proto_goTypes = []any{
	(Status)(0),                     // 0: poolmanager.Status
	(Type)(0),                       // 1: poolmanager.Type
	(*RessourceRequest)(nil),        // 2: poolmanager.RessourceRequest
	(*RessourceResponse)(nil),       // 3: poolmanager.RessourceResponse
	(*UserRequest)(nil),             // 4: poolmanager.UserRequest
	(*StreamRessourceResponse)(nil), // 5: poolmanager.StreamRessourceResponse
	(*Image)(nil),                   // 6: poolmanager.Image
	(*Flavor)(nil),                  // 7: poolmanager.Flavor
	(*Network)(nil),                 // 8: poolmanager.Network
	nil,                             // 9: poolmanager.RessourceRequest.DataEntry
	nil,                             // 10: poolmanager.StreamRessourceResponse.DataEntry
	(*timestamppb.Timestamp)(nil),   // 11: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 12: google.protobuf.Empty
}
var file_poolmanager_proto_depIdxs = []int32{
	9,  // 0: poolmanager.RessourceRequest.data:type_name -> poolmanager.RessourceRequest.DataEntry
	0,  // 1: poolmanager.RessourceRequest.status:type_name -> poolmanager.Status
	1,  // 2: poolmanager.RessourceRequest.type:type_name -> poolmanager.Type
	0,  // 3: poolmanager.StreamRessourceResponse.status:type_name -> poolmanager.Status
	1,  // 4: poolmanager.StreamRessourceResponse.type:type_name -> poolmanager.Type
	10, // 5: poolmanager.StreamRessourceResponse.data:type_name -> poolmanager.StreamRessourceResponse.DataEntry
	11, // 6: poolmanager.Image.created_at:type_name -> google.protobuf.Timestamp
	11, // 7: poolmanager.Image.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 8: poolmanager.PoolManager.SendRessources:input_type -> poolmanager.RessourceRequest
	12, // 9: poolmanager.PoolManager.GetStreamRessources:input_type -> google.protobuf.Empty
	4,  // 10: poolmanager.PoolManager.GetStreamRessourcesUser:input_type -> poolmanager.UserRequest
	12, // 11: poolmanager.PoolManager.GetAllImages:input_type -> google.protobuf.Empty
	12, // 12: poolmanager.PoolManager.GetAllFlavors:input_type -> google.protobuf.Empty
	12, // 13: poolmanager.PoolManager.GetAllNetworks:input_type -> google.protobuf.Empty
	3,  // 14: poolmanager.PoolManager.SendRessources:output_type -> poolmanager.RessourceResponse
	5,  // 15: poolmanager.PoolManager.GetStreamRessources:output_type -> poolmanager.StreamRessourceResponse
	5,  // 16: poolmanager.PoolManager.GetStreamRessourcesUser:output_type -> poolmanager.StreamRessourceResponse
	6,  // 17: poolmanager.PoolManager.GetAllImages:output_type -> poolmanager.Image
	7,  // 18: poolmanager.PoolManager.GetAllFlavors:output_type -> poolmanager.Flavor
	8,  // 19: poolmanager.PoolManager.GetAllNetworks:output_type -> poolmanager.Network
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_poolmanager_proto_init() }
func file_poolmanager_proto_init() {
	if File_poolmanager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_poolmanager_proto_rawDesc), len(file_poolmanager_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_poolmanager_proto_goTypes,
		DependencyIndexes: file_poolmanager_proto_depIdxs,
		EnumInfos:         file_poolmanager_proto_enumTypes,
		MessageInfos:      file_poolmanager_proto_msgTypes,
	}.Build()
	File_poolmanager_proto = out.File
	file_poolmanager_proto_goTypes = nil
	file_poolmanager_proto_depIdxs = nil
}
