// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: frontcontrol.proto

package frontcontrolpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNKNOWN Status = 0
	Status_CREATE         Status = 1
	Status_UPDATE         Status = 2
	Status_DELETE         Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "CREATE",
		2: "UPDATE",
		3: "DELETE",
	}
	Status_value = map[string]int32{
		"STATUS_UNKNOWN": 0,
		"CREATE":         1,
		"UPDATE":         2,
		"DELETE":         3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_frontcontrol_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_frontcontrol_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_frontcontrol_proto_rawDescGZIP(), []int{0}
}

type Type int32

const (
	Type_TYPE_UNKNOWN Type = 0
	Type_SERVERPOOL   Type = 1
	Type_SERVER       Type = 2
	Type_CONFIG       Type = 3
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "TYPE_UNKNOWN",
		1: "SERVERPOOL",
		2: "SERVER",
		3: "CONFIG",
	}
	Type_value = map[string]int32{
		"TYPE_UNKNOWN": 0,
		"SERVERPOOL":   1,
		"SERVER":       2,
		"CONFIG":       3,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_frontcontrol_proto_enumTypes[1].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_frontcontrol_proto_enumTypes[1]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_frontcontrol_proto_rawDescGZIP(), []int{1}
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_frontcontrol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontcontrol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_frontcontrol_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_frontcontrol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontcontrol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_frontcontrol_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AuthenticateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateUserRequest) Reset() {
	*x = AuthenticateUserRequest{}
	mi := &file_frontcontrol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateUserRequest) ProtoMessage() {}

func (x *AuthenticateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontcontrol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateUserRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateUserRequest) Descriptor() ([]byte, []int) {
	return file_frontcontrol_proto_rawDescGZIP(), []int{2}
}

func (x *AuthenticateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthenticateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthenticateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateUserResponse) Reset() {
	*x = AuthenticateUserResponse{}
	mi := &file_frontcontrol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateUserResponse) ProtoMessage() {}

func (x *AuthenticateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontcontrol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateUserResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateUserResponse) Descriptor() ([]byte, []int) {
	return file_frontcontrol_proto_rawDescGZIP(), []int{3}
}

func (x *AuthenticateUserResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthenticateUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Image struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status           string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Tags             string                 `protobuf:"bytes,4,opt,name=tags,proto3" json:"tags,omitempty"` // CSV format
	ContainerFormat  string                 `protobuf:"bytes,5,opt,name=container_format,json=containerFormat,proto3" json:"container_format,omitempty"`
	DiskFormat       string                 `protobuf:"bytes,6,opt,name=disk_format,json=diskFormat,proto3" json:"disk_format,omitempty"`
	MinDiskGigabytes int32                  `protobuf:"varint,7,opt,name=min_disk_gigabytes,json=minDiskGigabytes,proto3" json:"min_disk_gigabytes,omitempty"`
	MinRamMegabytes  int32                  `protobuf:"varint,8,opt,name=min_ram_megabytes,json=minRamMegabytes,proto3" json:"min_ram_megabytes,omitempty"`
	Owner            string                 `protobuf:"bytes,9,opt,name=owner,proto3" json:"owner,omitempty"`
	Protected        bool                   `protobuf:"varint,10,opt,name=protected,proto3" json:"protected,omitempty"`
	Visibility       string                 `protobuf:"bytes,11,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Hidden           bool                   `protobuf:"varint,12,opt,name=hidden,proto3" json:"hidden,omitempty"`
	Checksum         string                 `protobuf:"bytes,13,opt,name=checksum,proto3" json:"checksum,omitempty"`
	SizeBytes        int64                  `protobuf:"varint,14,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	File             string                 `protobuf:"bytes,17,opt,name=file,proto3" json:"file,omitempty"`
	Schema           string                 `protobuf:"bytes,18,opt,name=schema,proto3" json:"schema,omitempty"`
	VirtualSize      int64                  `protobuf:"varint,19,opt,name=virtual_size,json=virtualSize,proto3" json:"virtual_size,omitempty"`
	ImportMethods    string                 `protobuf:"bytes,20,opt,name=import_methods,json=importMethods,proto3" json:"import_methods,omitempty"` // CSV format
	StoreIds         string                 `protobuf:"bytes,21,opt,name=store_ids,json=storeIds,proto3" json:"store_ids,omitempty"`                // CSV format
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_frontcontrol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_frontcontrol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_frontcontrol_proto_rawDescGZIP(), []int{4}
}

func (x *Image) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Image) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Image) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Image) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *Image) GetContainerFormat() string {
	if x != nil {
		return x.ContainerFormat
	}
	return ""
}

func (x *Image) GetDiskFormat() string {
	if x != nil {
		return x.DiskFormat
	}
	return ""
}

func (x *Image) GetMinDiskGigabytes() int32 {
	if x != nil {
		return x.MinDiskGigabytes
	}
	return 0
}

func (x *Image) GetMinRamMegabytes() int32 {
	if x != nil {
		return x.MinRamMegabytes
	}
	return 0
}

func (x *Image) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Image) GetProtected() bool {
	if x != nil {
		return x.Protected
	}
	return false
}

func (x *Image) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *Image) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *Image) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *Image) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Image) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Image) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Image) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Image) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *Image) GetVirtualSize() int64 {
	if x != nil {
		return x.VirtualSize
	}
	return 0
}

func (x *Image) GetImportMethods() string {
	if x != nil {
		return x.ImportMethods
	}
	return ""
}

func (x *Image) GetStoreIds() string {
	if x != nil {
		return x.StoreIds
	}
	return ""
}

type Flavor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Disk          int32                  `protobuf:"varint,3,opt,name=disk,proto3" json:"disk,omitempty"`
	Ram           int32                  `protobuf:"varint,4,opt,name=ram,proto3" json:"ram,omitempty"`
	Vcpus         int32                  `protobuf:"varint,5,opt,name=vcpus,proto3" json:"vcpus,omitempty"`
	RxtxFactor    float64                `protobuf:"fixed64,6,opt,name=rxtx_factor,json=rxtxFactor,proto3" json:"rxtx_factor,omitempty"`
	Swap          int32                  `protobuf:"varint,7,opt,name=swap,proto3" json:"swap,omitempty"`
	Ephemeral     int32                  `protobuf:"varint,8,opt,name=ephemeral,proto3" json:"ephemeral,omitempty"`
	IsPublic      bool                   `protobuf:"varint,9,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	Description   string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	ExtraSpecs    string                 `protobuf:"bytes,11,opt,name=extra_specs,json=extraSpecs,proto3" json:"extra_specs,omitempty"` // JSON serialized
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flavor) Reset() {
	*x = Flavor{}
	mi := &file_frontcontrol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flavor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flavor) ProtoMessage() {}

func (x *Flavor) ProtoReflect() protoreflect.Message {
	mi := &file_frontcontrol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flavor.ProtoReflect.Descriptor instead.
func (*Flavor) Descriptor() ([]byte, []int) {
	return file_frontcontrol_proto_rawDescGZIP(), []int{5}
}

func (x *Flavor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Flavor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Flavor) GetDisk() int32 {
	if x != nil {
		return x.Disk
	}
	return 0
}

func (x *Flavor) GetRam() int32 {
	if x != nil {
		return x.Ram
	}
	return 0
}

func (x *Flavor) GetVcpus() int32 {
	if x != nil {
		return x.Vcpus
	}
	return 0
}

func (x *Flavor) GetRxtxFactor() float64 {
	if x != nil {
		return x.RxtxFactor
	}
	return 0
}

func (x *Flavor) GetSwap() int32 {
	if x != nil {
		return x.Swap
	}
	return 0
}

func (x *Flavor) GetEphemeral() int32 {
	if x != nil {
		return x.Ephemeral
	}
	return 0
}

func (x *Flavor) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *Flavor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Flavor) GetExtraSpecs() string {
	if x != nil {
		return x.ExtraSpecs
	}
	return ""
}

type Network struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description           string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AdminStateUp          bool                   `protobuf:"varint,4,opt,name=admin_state_up,json=adminStateUp,proto3" json:"admin_state_up,omitempty"`
	Status                string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	TenantId              string                 `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ProjectId             string                 `protobuf:"bytes,7,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Shared                bool                   `protobuf:"varint,8,opt,name=shared,proto3" json:"shared,omitempty"`
	RevisionNumber        int32                  `protobuf:"varint,9,opt,name=revision_number,json=revisionNumber,proto3" json:"revision_number,omitempty"`
	Subnets               string                 `protobuf:"bytes,10,opt,name=subnets,proto3" json:"subnets,omitempty"`                                                            // CSV
	AvailabilityZoneHints string                 `protobuf:"bytes,11,opt,name=availability_zone_hints,json=availabilityZoneHints,proto3" json:"availability_zone_hints,omitempty"` // CSV
	Tags                  string                 `protobuf:"bytes,12,opt,name=tags,proto3" json:"tags,omitempty"`                                                                  // CSV
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Network) Reset() {
	*x = Network{}
	mi := &file_frontcontrol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network) ProtoMessage() {}

func (x *Network) ProtoReflect() protoreflect.Message {
	mi := &file_frontcontrol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network.ProtoReflect.Descriptor instead.
func (*Network) Descriptor() ([]byte, []int) {
	return file_frontcontrol_proto_rawDescGZIP(), []int{6}
}

func (x *Network) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Network) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Network) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Network) GetAdminStateUp() bool {
	if x != nil {
		return x.AdminStateUp
	}
	return false
}

func (x *Network) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Network) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Network) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Network) GetShared() bool {
	if x != nil {
		return x.Shared
	}
	return false
}

func (x *Network) GetRevisionNumber() int32 {
	if x != nil {
		return x.RevisionNumber
	}
	return 0
}

func (x *Network) GetSubnets() string {
	if x != nil {
		return x.Subnets
	}
	return ""
}

func (x *Network) GetAvailabilityZoneHints() string {
	if x != nil {
		return x.AvailabilityZoneHints
	}
	return ""
}

func (x *Network) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

type CreateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConfigRequest) Reset() {
	*x = CreateConfigRequest{}
	mi := &file_frontcontrol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConfigRequest) ProtoMessage() {}

func (x *CreateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontcontrol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConfigRequest.ProtoReflect.Descriptor instead.
func (*CreateConfigRequest) Descriptor() ([]byte, []int) {
	return file_frontcontrol_proto_rawDescGZIP(), []int{7}
}

func (x *CreateConfigRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *CreateConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateConfigRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CreateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConfigResponse) Reset() {
	*x = CreateConfigResponse{}
	mi := &file_frontcontrol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConfigResponse) ProtoMessage() {}

func (x *CreateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontcontrol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConfigResponse.ProtoReflect.Descriptor instead.
func (*CreateConfigResponse) Descriptor() ([]byte, []int) {
	return file_frontcontrol_proto_rawDescGZIP(), []int{8}
}

func (x *CreateConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_frontcontrol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontcontrol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_frontcontrol_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateConfigRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *UpdateConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpdateConfigRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UpdateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigResponse) Reset() {
	*x = UpdateConfigResponse{}
	mi := &file_frontcontrol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigResponse) ProtoMessage() {}

func (x *UpdateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontcontrol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigResponse) Descriptor() ([]byte, []int) {
	return file_frontcontrol_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigRequest) Reset() {
	*x = DeleteConfigRequest{}
	mi := &file_frontcontrol_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigRequest) ProtoMessage() {}

func (x *DeleteConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontcontrol_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigRequest.ProtoReflect.Descriptor instead.
func (*DeleteConfigRequest) Descriptor() ([]byte, []int) {
	return file_frontcontrol_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteConfigRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *DeleteConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigResponse) Reset() {
	*x = DeleteConfigResponse{}
	mi := &file_frontcontrol_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigResponse) ProtoMessage() {}

func (x *DeleteConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontcontrol_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigResponse.ProtoReflect.Descriptor instead.
func (*DeleteConfigResponse) Descriptor() ([]byte, []int) {
	return file_frontcontrol_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_frontcontrol_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontcontrol_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_frontcontrol_proto_rawDescGZIP(), []int{13}
}

func (x *GetConfigRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *GetConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_frontcontrol_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontcontrol_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_frontcontrol_proto_rawDescGZIP(), []int{14}
}

func (x *GetConfigResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetConfigResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type CreatePoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Flavor        string                 `protobuf:"bytes,4,opt,name=flavor,proto3" json:"flavor,omitempty"`
	Network       string                 `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	Config        string                 `protobuf:"bytes,6,opt,name=config,proto3" json:"config,omitempty"`
	MinVm         string                 `protobuf:"bytes,7,opt,name=min_vm,json=minVm,proto3" json:"min_vm,omitempty"`
	MaxVm         string                 `protobuf:"bytes,8,opt,name=max_vm,json=maxVm,proto3" json:"max_vm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePoolRequest) Reset() {
	*x = CreatePoolRequest{}
	mi := &file_frontcontrol_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePoolRequest) ProtoMessage() {}

func (x *CreatePoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontcontrol_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePoolRequest.ProtoReflect.Descriptor instead.
func (*CreatePoolRequest) Descriptor() ([]byte, []int) {
	return file_frontcontrol_proto_rawDescGZIP(), []int{15}
}

func (x *CreatePoolRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *CreatePoolRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePoolRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreatePoolRequest) GetFlavor() string {
	if x != nil {
		return x.Flavor
	}
	return ""
}

func (x *CreatePoolRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *CreatePoolRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *CreatePoolRequest) GetMinVm() string {
	if x != nil {
		return x.MinVm
	}
	return ""
}

func (x *CreatePoolRequest) GetMaxVm() string {
	if x != nil {
		return x.MaxVm
	}
	return ""
}

type CreatePoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        string                 `protobuf:"bytes,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePoolResponse) Reset() {
	*x = CreatePoolResponse{}
	mi := &file_frontcontrol_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePoolResponse) ProtoMessage() {}

func (x *CreatePoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontcontrol_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePoolResponse.ProtoReflect.Descriptor instead.
func (*CreatePoolResponse) Descriptor() ([]byte, []int) {
	return file_frontcontrol_proto_rawDescGZIP(), []int{16}
}

func (x *CreatePoolResponse) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *CreatePoolResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeletePoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	PoolId        string                 `protobuf:"bytes,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePoolRequest) Reset() {
	*x = DeletePoolRequest{}
	mi := &file_frontcontrol_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePoolRequest) ProtoMessage() {}

func (x *DeletePoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontcontrol_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePoolRequest.ProtoReflect.Descriptor instead.
func (*DeletePoolRequest) Descriptor() ([]byte, []int) {
	return file_frontcontrol_proto_rawDescGZIP(), []int{17}
}

func (x *DeletePoolRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *DeletePoolRequest) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

type DeletePoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePoolResponse) Reset() {
	*x = DeletePoolResponse{}
	mi := &file_frontcontrol_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePoolResponse) ProtoMessage() {}

func (x *DeletePoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontcontrol_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePoolResponse.ProtoReflect.Descriptor instead.
func (*DeletePoolResponse) Descriptor() ([]byte, []int) {
	return file_frontcontrol_proto_rawDescGZIP(), []int{18}
}

func (x *DeletePoolResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetPoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	PoolId        string                 `protobuf:"bytes,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPoolRequest) Reset() {
	*x = GetPoolRequest{}
	mi := &file_frontcontrol_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoolRequest) ProtoMessage() {}

func (x *GetPoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontcontrol_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPoolRequest.ProtoReflect.Descriptor instead.
func (*GetPoolRequest) Descriptor() ([]byte, []int) {
	return file_frontcontrol_proto_rawDescGZIP(), []int{19}
}

func (x *GetPoolRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *GetPoolRequest) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

type GetPoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Flavor        string                 `protobuf:"bytes,3,opt,name=flavor,proto3" json:"flavor,omitempty"`
	Network       string                 `protobuf:"bytes,4,opt,name=network,proto3" json:"network,omitempty"`
	Config        string                 `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	MinVm         int32                  `protobuf:"varint,6,opt,name=min_vm,json=minVm,proto3" json:"min_vm,omitempty"`
	MaxVm         int32                  `protobuf:"varint,7,opt,name=max_vm,json=maxVm,proto3" json:"max_vm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPoolResponse) Reset() {
	*x = GetPoolResponse{}
	mi := &file_frontcontrol_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoolResponse) ProtoMessage() {}

func (x *GetPoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontcontrol_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPoolResponse.ProtoReflect.Descriptor instead.
func (*GetPoolResponse) Descriptor() ([]byte, []int) {
	return file_frontcontrol_proto_rawDescGZIP(), []int{20}
}

func (x *GetPoolResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPoolResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *GetPoolResponse) GetFlavor() string {
	if x != nil {
		return x.Flavor
	}
	return ""
}

func (x *GetPoolResponse) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *GetPoolResponse) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *GetPoolResponse) GetMinVm() int32 {
	if x != nil {
		return x.MinVm
	}
	return 0
}

func (x *GetPoolResponse) GetMaxVm() int32 {
	if x != nil {
		return x.MaxVm
	}
	return 0
}

type UpdateDataUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDataUserRequest) Reset() {
	*x = UpdateDataUserRequest{}
	mi := &file_frontcontrol_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDataUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataUserRequest) ProtoMessage() {}

func (x *UpdateDataUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontcontrol_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateDataUserRequest) Descriptor() ([]byte, []int) {
	return file_frontcontrol_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateDataUserRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type UpdateDataUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=frontcontrol.Status" json:"status,omitempty"`
	Type          Type                   `protobuf:"varint,3,opt,name=type,proto3,enum=frontcontrol.Type" json:"type,omitempty"`
	Data          map[string]string      `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDataUserResponse) Reset() {
	*x = UpdateDataUserResponse{}
	mi := &file_frontcontrol_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDataUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataUserResponse) ProtoMessage() {}

func (x *UpdateDataUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontcontrol_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateDataUserResponse) Descriptor() ([]byte, []int) {
	return file_frontcontrol_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateDataUserResponse) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *UpdateDataUserResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNKNOWN
}

func (x *UpdateDataUserResponse) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_TYPE_UNKNOWN
}

func (x *UpdateDataUserResponse) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type RebuildServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	PoolId        string                 `protobuf:"bytes,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebuildServerRequest) Reset() {
	*x = RebuildServerRequest{}
	mi := &file_frontcontrol_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebuildServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebuildServerRequest) ProtoMessage() {}

func (x *RebuildServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontcontrol_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebuildServerRequest.ProtoReflect.Descriptor instead.
func (*RebuildServerRequest) Descriptor() ([]byte, []int) {
	return file_frontcontrol_proto_rawDescGZIP(), []int{23}
}

func (x *RebuildServerRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *RebuildServerRequest) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *RebuildServerRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type RebuildServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebuildServerResponse) Reset() {
	*x = RebuildServerResponse{}
	mi := &file_frontcontrol_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebuildServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebuildServerResponse) ProtoMessage() {}

func (x *RebuildServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontcontrol_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebuildServerResponse.ProtoReflect.Descriptor instead.
func (*RebuildServerResponse) Descriptor() ([]byte, []int) {
	return file_frontcontrol_proto_rawDescGZIP(), []int{24}
}

func (x *RebuildServerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_frontcontrol_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontcontrol_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_frontcontrol_proto_rawDescGZIP(), []int{25}
}

func (x *UserRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Flavor        string                 `protobuf:"bytes,5,opt,name=flavor,proto3" json:"flavor,omitempty"`
	Network       string                 `protobuf:"bytes,6,opt,name=network,proto3" json:"network,omitempty"`
	IpAddress     string                 `protobuf:"bytes,7,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_frontcontrol_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_frontcontrol_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_frontcontrol_proto_rawDescGZIP(), []int{26}
}

func (x *Server) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Server) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Server) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Server) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Server) GetFlavor() string {
	if x != nil {
		return x.Flavor
	}
	return ""
}

func (x *Server) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Server) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Server) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Server) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ServerPool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Flavor        string                 `protobuf:"bytes,4,opt,name=flavor,proto3" json:"flavor,omitempty"`
	Network       string                 `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	Config        string                 `protobuf:"bytes,6,opt,name=config,proto3" json:"config,omitempty"`
	MinVm         int32                  `protobuf:"varint,7,opt,name=min_vm,json=minVm,proto3" json:"min_vm,omitempty"`
	MaxVm         int32                  `protobuf:"varint,8,opt,name=max_vm,json=maxVm,proto3" json:"max_vm,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPool) Reset() {
	*x = ServerPool{}
	mi := &file_frontcontrol_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPool) ProtoMessage() {}

func (x *ServerPool) ProtoReflect() protoreflect.Message {
	mi := &file_frontcontrol_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPool.ProtoReflect.Descriptor instead.
func (*ServerPool) Descriptor() ([]byte, []int) {
	return file_frontcontrol_proto_rawDescGZIP(), []int{27}
}

func (x *ServerPool) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServerPool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerPool) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ServerPool) GetFlavor() string {
	if x != nil {
		return x.Flavor
	}
	return ""
}

func (x *ServerPool) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *ServerPool) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *ServerPool) GetMinVm() int32 {
	if x != nil {
		return x.MinVm
	}
	return 0
}

func (x *ServerPool) GetMaxVm() int32 {
	if x != nil {
		return x.MaxVm
	}
	return 0
}

func (x *ServerPool) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_frontcontrol_proto protoreflect.FileDescriptor

const file_frontcontrol_proto_rawDesc = "" +
	"\n" +
	"\x12frontcontrol.proto\x12\ffrontcontrol\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"a\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"G\n" +
	"\x12CreateUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"K\n" +
	"\x17AuthenticateUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"J\n" +
	"\x18AuthenticateUserResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\xad\x05\n" +
	"\x05Image\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04tags\x18\x04 \x01(\tR\x04tags\x12)\n" +
	"\x10container_format\x18\x05 \x01(\tR\x0fcontainerFormat\x12\x1f\n" +
	"\vdisk_format\x18\x06 \x01(\tR\n" +
	"diskFormat\x12,\n" +
	"\x12min_disk_gigabytes\x18\a \x01(\x05R\x10minDiskGigabytes\x12*\n" +
	"\x11min_ram_megabytes\x18\b \x01(\x05R\x0fminRamMegabytes\x12\x14\n" +
	"\x05owner\x18\t \x01(\tR\x05owner\x12\x1c\n" +
	"\tprotected\x18\n" +
	" \x01(\bR\tprotected\x12\x1e\n" +
	"\n" +
	"visibility\x18\v \x01(\tR\n" +
	"visibility\x12\x16\n" +
	"\x06hidden\x18\f \x01(\bR\x06hidden\x12\x1a\n" +
	"\bchecksum\x18\r \x01(\tR\bchecksum\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x0e \x01(\x03R\tsizeBytes\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x12\n" +
	"\x04file\x18\x11 \x01(\tR\x04file\x12\x16\n" +
	"\x06schema\x18\x12 \x01(\tR\x06schema\x12!\n" +
	"\fvirtual_size\x18\x13 \x01(\x03R\vvirtualSize\x12%\n" +
	"\x0eimport_methods\x18\x14 \x01(\tR\rimportMethods\x12\x1b\n" +
	"\tstore_ids\x18\x15 \x01(\tR\bstoreIds\"\x9b\x02\n" +
	"\x06Flavor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04disk\x18\x03 \x01(\x05R\x04disk\x12\x10\n" +
	"\x03ram\x18\x04 \x01(\x05R\x03ram\x12\x14\n" +
	"\x05vcpus\x18\x05 \x01(\x05R\x05vcpus\x12\x1f\n" +
	"\vrxtx_factor\x18\x06 \x01(\x01R\n" +
	"rxtxFactor\x12\x12\n" +
	"\x04swap\x18\a \x01(\x05R\x04swap\x12\x1c\n" +
	"\tephemeral\x18\b \x01(\x05R\tephemeral\x12\x1b\n" +
	"\tis_public\x18\t \x01(\bR\bisPublic\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12\x1f\n" +
	"\vextra_specs\x18\v \x01(\tR\n" +
	"extraSpecs\"\xf0\x02\n" +
	"\aNetwork\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12$\n" +
	"\x0eadmin_state_up\x18\x04 \x01(\bR\fadminStateUp\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"project_id\x18\a \x01(\tR\tprojectId\x12\x16\n" +
	"\x06shared\x18\b \x01(\bR\x06shared\x12'\n" +
	"\x0frevision_number\x18\t \x01(\x05R\x0erevisionNumber\x12\x18\n" +
	"\asubnets\x18\n" +
	" \x01(\tR\asubnets\x126\n" +
	"\x17availability_zone_hints\x18\v \x01(\tR\x15availabilityZoneHints\x12\x12\n" +
	"\x04tags\x18\f \x01(\tR\x04tags\"Q\n" +
	"\x13CreateConfigRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"0\n" +
	"\x14CreateConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Q\n" +
	"\x13UpdateConfigRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"0\n" +
	"\x14UpdateConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\";\n" +
	"\x13DeleteConfigRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"0\n" +
	"\x14DeleteConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"8\n" +
	"\x10GetConfigRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\";\n" +
	"\x11GetConfigResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\xc9\x01\n" +
	"\x11CreatePoolRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x16\n" +
	"\x06flavor\x18\x04 \x01(\tR\x06flavor\x12\x18\n" +
	"\anetwork\x18\x05 \x01(\tR\anetwork\x12\x16\n" +
	"\x06config\x18\x06 \x01(\tR\x06config\x12\x15\n" +
	"\x06min_vm\x18\a \x01(\tR\x05minVm\x12\x15\n" +
	"\x06max_vm\x18\b \x01(\tR\x05maxVm\"G\n" +
	"\x12CreatePoolResponse\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\tR\x06poolId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"@\n" +
	"\x11DeletePoolRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x17\n" +
	"\apool_id\x18\x02 \x01(\tR\x06poolId\".\n" +
	"\x12DeletePoolResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"=\n" +
	"\x0eGetPoolRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x17\n" +
	"\apool_id\x18\x02 \x01(\tR\x06poolId\"\xb9\x01\n" +
	"\x0fGetPoolResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x16\n" +
	"\x06flavor\x18\x03 \x01(\tR\x06flavor\x12\x18\n" +
	"\anetwork\x18\x04 \x01(\tR\anetwork\x12\x16\n" +
	"\x06config\x18\x05 \x01(\tR\x06config\x12\x15\n" +
	"\x06min_vm\x18\x06 \x01(\x05R\x05minVm\x12\x15\n" +
	"\x06max_vm\x18\a \x01(\x05R\x05maxVmJ\x04\b\b\x10\t\"+\n" +
	"\x15UpdateDataUserRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\"\xff\x01\n" +
	"\x16UpdateDataUserResponse\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.frontcontrol.StatusR\x06status\x12&\n" +
	"\x04type\x18\x03 \x01(\x0e2\x12.frontcontrol.TypeR\x04type\x12B\n" +
	"\x04data\x18\x04 \x03(\v2..frontcontrol.UpdateDataUserResponse.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"`\n" +
	"\x14RebuildServerRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x17\n" +
	"\apool_id\x18\x02 \x01(\tR\x06poolId\x12\x1b\n" +
	"\tserver_id\x18\x03 \x01(\tR\bserverId\"1\n" +
	"\x15RebuildServerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"!\n" +
	"\vUserRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\"\x9e\x03\n" +
	"\x06Server\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12\x16\n" +
	"\x06flavor\x18\x05 \x01(\tR\x06flavor\x12\x18\n" +
	"\anetwork\x18\x06 \x01(\tR\anetwork\x12\x1d\n" +
	"\n" +
	"ip_address\x18\a \x01(\tR\tipAddress\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12>\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2\".frontcontrol.Server.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbf\x02\n" +
	"\n" +
	"ServerPool\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x16\n" +
	"\x06flavor\x18\x04 \x01(\tR\x06flavor\x12\x18\n" +
	"\anetwork\x18\x05 \x01(\tR\anetwork\x12\x16\n" +
	"\x06config\x18\x06 \x01(\tR\x06config\x12\x15\n" +
	"\x06min_vm\x18\a \x01(\x05R\x05minVm\x12\x15\n" +
	"\x06max_vm\x18\b \x01(\x05R\x05maxVm\x12B\n" +
	"\bmetadata\x18\t \x03(\v2&.frontcontrol.ServerPool.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*@\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06CREATE\x10\x01\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x03*@\n" +
	"\x04Type\x12\x10\n" +
	"\fTYPE_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"SERVERPOOL\x10\x01\x12\n" +
	"\n" +
	"\x06SERVER\x10\x02\x12\n" +
	"\n" +
	"\x06CONFIG\x10\x032\xc1\x01\n" +
	"\vAuthService\x12O\n" +
	"\n" +
	"CreateUser\x12\x1f.frontcontrol.CreateUserRequest\x1a .frontcontrol.CreateUserResponse\x12a\n" +
	"\x10AuthenticateUser\x12%.frontcontrol.AuthenticateUserRequest\x1a&.frontcontrol.AuthenticateUserResponse2\xe6\x02\n" +
	"\x11GatherDataService\x12=\n" +
	"\fGetAllImages\x12\x16.google.protobuf.Empty\x1a\x13.frontcontrol.Image0\x01\x12?\n" +
	"\rGetAllFlavors\x12\x16.google.protobuf.Empty\x1a\x14.frontcontrol.Flavor0\x01\x12A\n" +
	"\x0eGetAllNetworks\x12\x16.google.protobuf.Empty\x1a\x15.frontcontrol.Network0\x01\x12B\n" +
	"\rGetAllServers\x12\x19.frontcontrol.UserRequest\x1a\x14.frontcontrol.Server0\x01\x12J\n" +
	"\x11GetAllServerPools\x12\x19.frontcontrol.UserRequest\x1a\x18.frontcontrol.ServerPool0\x012\xb6\x03\n" +
	"\rConfigService\x12U\n" +
	"\fCreateConfig\x12!.frontcontrol.CreateConfigRequest\x1a\".frontcontrol.CreateConfigResponse\x12U\n" +
	"\fUpdateConfig\x12!.frontcontrol.UpdateConfigRequest\x1a\".frontcontrol.UpdateConfigResponse\x12U\n" +
	"\fDeleteConfig\x12!.frontcontrol.DeleteConfigRequest\x1a\".frontcontrol.DeleteConfigResponse\x12L\n" +
	"\tGetConfig\x12\x1e.frontcontrol.GetConfigRequest\x1a\x1f.frontcontrol.GetConfigResponse\x12R\n" +
	"\rGetAllConfigs\x12\x1e.frontcontrol.GetConfigRequest\x1a\x1f.frontcontrol.GetConfigResponse0\x012\x9f\x03\n" +
	"\vPoolService\x12O\n" +
	"\n" +
	"CreatePool\x12\x1f.frontcontrol.CreatePoolRequest\x1a .frontcontrol.CreatePoolResponse\x12F\n" +
	"\aGetPool\x12\x1c.frontcontrol.GetPoolRequest\x1a\x1d.frontcontrol.GetPoolResponse\x12L\n" +
	"\vGetAllPools\x12\x1c.frontcontrol.GetPoolRequest\x1a\x1d.frontcontrol.GetPoolResponse0\x01\x12O\n" +
	"\n" +
	"DeletePool\x12\x1f.frontcontrol.DeletePoolRequest\x1a .frontcontrol.DeletePoolResponse\x12X\n" +
	"\rRebuildServer\x12\".frontcontrol.RebuildServerRequest\x1a#.frontcontrol.RebuildServerResponse2l\n" +
	"\vUserService\x12]\n" +
	"\x0eUpdateDataUser\x12#.frontcontrol.UpdateDataUserRequest\x1a$.frontcontrol.UpdateDataUserResponse0\x01B\x12Z\x10./frontcontrolpbb\x06proto3"

var (
	file_frontcontrol_proto_rawDescOnce sync.Once
	file_frontcontrol_proto_rawDescData []byte
)

func file_frontcontrol_proto_rawDescGZIP() []byte {
	file_frontcontrol_proto_rawDescOnce.Do(func() {
		file_frontcontrol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_frontcontrol_proto_rawDesc), len(file_frontcontrol_proto_rawDesc)))
	})
	return file_frontcontrol_proto_rawDescData
}

var file_frontcontrol_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_frontcontrol_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_frontcontrol_proto_goTypes = []any{
	(Status)(0),                      // 0: frontcontrol.Status
	(Type)(0),                        // 1: frontcontrol.Type
	(*CreateUserRequest)(nil),        // 2: frontcontrol.CreateUserRequest
	(*CreateUserResponse)(nil),       // 3: frontcontrol.CreateUserResponse
	(*AuthenticateUserRequest)(nil),  // 4: frontcontrol.AuthenticateUserRequest
	(*AuthenticateUserResponse)(nil), // 5: frontcontrol.AuthenticateUserResponse
	(*Image)(nil),                    // 6: frontcontrol.Image
	(*Flavor)(nil),                   // 7: frontcontrol.Flavor
	(*Network)(nil),                  // 8: frontcontrol.Network
	(*CreateConfigRequest)(nil),      // 9: frontcontrol.CreateConfigRequest
	(*CreateConfigResponse)(nil),     // 10: frontcontrol.CreateConfigResponse
	(*UpdateConfigRequest)(nil),      // 11: frontcontrol.UpdateConfigRequest
	(*UpdateConfigResponse)(nil),     // 12: frontcontrol.UpdateConfigResponse
	(*DeleteConfigRequest)(nil),      // 13: frontcontrol.DeleteConfigRequest
	(*DeleteConfigResponse)(nil),     // 14: frontcontrol.DeleteConfigResponse
	(*GetConfigRequest)(nil),         // 15: frontcontrol.GetConfigRequest
	(*GetConfigResponse)(nil),        // 16: frontcontrol.GetConfigResponse
	(*CreatePoolRequest)(nil),        // 17: frontcontrol.CreatePoolRequest
	(*CreatePoolResponse)(nil),       // 18: frontcontrol.CreatePoolResponse
	(*DeletePoolRequest)(nil),        // 19: frontcontrol.DeletePoolRequest
	(*DeletePoolResponse)(nil),       // 20: frontcontrol.DeletePoolResponse
	(*GetPoolRequest)(nil),           // 21: frontcontrol.GetPoolRequest
	(*GetPoolResponse)(nil),          // 22: frontcontrol.GetPoolResponse
	(*UpdateDataUserRequest)(nil),    // 23: frontcontrol.UpdateDataUserRequest
	(*UpdateDataUserResponse)(nil),   // 24: frontcontrol.UpdateDataUserResponse
	(*RebuildServerRequest)(nil),     // 25: frontcontrol.RebuildServerRequest
	(*RebuildServerResponse)(nil),    // 26: frontcontrol.RebuildServerResponse
	(*UserRequest)(nil),              // 27: frontcontrol.UserRequest
	(*Server)(nil),                   // 28: frontcontrol.Server
	(*ServerPool)(nil),               // 29: frontcontrol.ServerPool
	nil,                              // 30: frontcontrol.UpdateDataUserResponse.DataEntry
	nil,                              // 31: frontcontrol.Server.MetadataEntry
	nil,                              // 32: frontcontrol.ServerPool.MetadataEntry
	(*timestamppb.Timestamp)(nil),    // 33: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 34: google.protobuf.Empty
}
var file_frontcontrol_proto_depIdxs = []int32{
	33, // 0: frontcontrol.Image.created_at:type_name -> google.protobuf.Timestamp
	33, // 1: frontcontrol.Image.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: frontcontrol.UpdateDataUserResponse.status:type_name -> frontcontrol.Status
	1,  // 3: frontcontrol.UpdateDataUserResponse.type:type_name -> frontcontrol.Type
	30, // 4: frontcontrol.UpdateDataUserResponse.data:type_name -> frontcontrol.UpdateDataUserResponse.DataEntry
	33, // 5: frontcontrol.Server.created_at:type_name -> google.protobuf.Timestamp
	33, // 6: frontcontrol.Server.updated_at:type_name -> google.protobuf.Timestamp
	31, // 7: frontcontrol.Server.metadata:type_name -> frontcontrol.Server.MetadataEntry
	32, // 8: frontcontrol.ServerPool.metadata:type_name -> frontcontrol.ServerPool.MetadataEntry
	2,  // 9: frontcontrol.AuthService.CreateUser:input_type -> frontcontrol.CreateUserRequest
	4,  // 10: frontcontrol.AuthService.AuthenticateUser:input_type -> frontcontrol.AuthenticateUserRequest
	34, // 11: frontcontrol.GatherDataService.GetAllImages:input_type -> google.protobuf.Empty
	34, // 12: frontcontrol.GatherDataService.GetAllFlavors:input_type -> google.protobuf.Empty
	34, // 13: frontcontrol.GatherDataService.GetAllNetworks:input_type -> google.protobuf.Empty
	27, // 14: frontcontrol.GatherDataService.GetAllServers:input_type -> frontcontrol.UserRequest
	27, // 15: frontcontrol.GatherDataService.GetAllServerPools:input_type -> frontcontrol.UserRequest
	9,  // 16: frontcontrol.ConfigService.CreateConfig:input_type -> frontcontrol.CreateConfigRequest
	11, // 17: frontcontrol.ConfigService.UpdateConfig:input_type -> frontcontrol.UpdateConfigRequest
	13, // 18: frontcontrol.ConfigService.DeleteConfig:input_type -> frontcontrol.DeleteConfigRequest
	15, // 19: frontcontrol.ConfigService.GetConfig:input_type -> frontcontrol.GetConfigRequest
	15, // 20: frontcontrol.ConfigService.GetAllConfigs:input_type -> frontcontrol.GetConfigRequest
	17, // 21: frontcontrol.PoolService.CreatePool:input_type -> frontcontrol.CreatePoolRequest
	21, // 22: frontcontrol.PoolService.GetPool:input_type -> frontcontrol.GetPoolRequest
	21, // 23: frontcontrol.PoolService.GetAllPools:input_type -> frontcontrol.GetPoolRequest
	19, // 24: frontcontrol.PoolService.DeletePool:input_type -> frontcontrol.DeletePoolRequest
	25, // 25: frontcontrol.PoolService.RebuildServer:input_type -> frontcontrol.RebuildServerRequest
	23, // 26: frontcontrol.UserService.UpdateDataUser:input_type -> frontcontrol.UpdateDataUserRequest
	3,  // 27: frontcontrol.AuthService.CreateUser:output_type -> frontcontrol.CreateUserResponse
	5,  // 28: frontcontrol.AuthService.AuthenticateUser:output_type -> frontcontrol.AuthenticateUserResponse
	6,  // 29: frontcontrol.GatherDataService.GetAllImages:output_type -> frontcontrol.Image
	7,  // 30: frontcontrol.GatherDataService.GetAllFlavors:output_type -> frontcontrol.Flavor
	8,  // 31: frontcontrol.GatherDataService.GetAllNetworks:output_type -> frontcontrol.Network
	28, // 32: frontcontrol.GatherDataService.GetAllServers:output_type -> frontcontrol.Server
	29, // 33: frontcontrol.GatherDataService.GetAllServerPools:output_type -> frontcontrol.ServerPool
	10, // 34: frontcontrol.ConfigService.CreateConfig:output_type -> frontcontrol.CreateConfigResponse
	12, // 35: frontcontrol.ConfigService.UpdateConfig:output_type -> frontcontrol.UpdateConfigResponse
	14, // 36: frontcontrol.ConfigService.DeleteConfig:output_type -> frontcontrol.DeleteConfigResponse
	16, // 37: frontcontrol.ConfigService.GetConfig:output_type -> frontcontrol.GetConfigResponse
	16, // 38: frontcontrol.ConfigService.GetAllConfigs:output_type -> frontcontrol.GetConfigResponse
	18, // 39: frontcontrol.PoolService.CreatePool:output_type -> frontcontrol.CreatePoolResponse
	22, // 40: frontcontrol.PoolService.GetPool:output_type -> frontcontrol.GetPoolResponse
	22, // 41: frontcontrol.PoolService.GetAllPools:output_type -> frontcontrol.GetPoolResponse
	20, // 42: frontcontrol.PoolService.DeletePool:output_type -> frontcontrol.DeletePoolResponse
	26, // 43: frontcontrol.PoolService.RebuildServer:output_type -> frontcontrol.RebuildServerResponse
	24, // 44: frontcontrol.UserService.UpdateDataUser:output_type -> frontcontrol.UpdateDataUserResponse
	27, // [27:45] is the sub-list for method output_type
	9,  // [9:27] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_frontcontrol_proto_init() }
func file_frontcontrol_proto_init() {
	if File_frontcontrol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_frontcontrol_proto_rawDesc), len(file_frontcontrol_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_frontcontrol_proto_goTypes,
		DependencyIndexes: file_frontcontrol_proto_depIdxs,
		EnumInfos:         file_frontcontrol_proto_enumTypes,
		MessageInfos:      file_frontcontrol_proto_msgTypes,
	}.Build()
	File_frontcontrol_proto = out.File
	file_frontcontrol_proto_goTypes = nil
	file_frontcontrol_proto_depIdxs = nil
}
